title: MOJ technical guidance

permalink: pretty

header_links:
  GitHub: https://github.com/ministryofjustice/technical-guidance

defaults:
  -
    scope:
      path: "standards"
    values:
      standard: true
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "principles"
    values:
      principle: true
